### ISSUE TITLE
Chore: loosen dependency restrictions

### ISSUE THREAD

**Issue by florianbepunkt** [BlackBoxVision/react-qr-reader#16]
Could you loosen the peerDependency restrictions? Currently @zxing/browser is pinned to version : 0.0.7. This sort of breaks our CI environment, where we use renovate and an extensive test suite to automate dependency updates. NPM7 has reverted back to installing peer dependencies – which fails, since @zxing/browser is pinned.

From basic testing I see no issues arising from using a newer version of @zxing/browser. Was there a specific reason to require this exact version?

**Comment by JonatanSalas** [comment]
No, there was no specific reason to do so, it's a bug, I'll fix it as soon as i can.

**Comment by JonatanSalas** [comment]
I think with the latest commit should be fixed, would you mind to test this version: `@blackbox-vision/react-qr-reader@4.1.1`?

**Comment by florianbepunkt** [comment]
Still getting the error

In my package.json (shortened for clarity)

```json
dependencies: {
    "@blackbox-vision/react-qr-reader": "4.1.1",
    "@zxing/browser": "0.0.9",
    "@zxing/library": "0.18.6",
}
```

```
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @herakles/customer-facing-ui@1.0.1
npm ERR! Found: @zxing/browser@0.0.9
npm ERR! node_modules/@zxing/browser
npm ERR!   @zxing/browser@"0.0.9" from @herakles/customer-facing-ui@1.0.1
npm ERR!   packages/customer-facing-ui
npm ERR!     @herakles/customer-facing-ui@1.0.1
npm ERR!     node_modules/@herakles/customer-facing-ui
npm ERR!       workspace packages/customer-facing-ui from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @zxing/browser@"^0.0.7" from @blackbox-vision/react-qr-reader@4.1.1
npm ERR! node_modules/@blackbox-vision/react-qr-reader
npm ERR!   @blackbox-vision/react-qr-reader@"4.1.1" from @herakles/customer-facing-ui@1.0.1
npm ERR!   packages/customer-facing-ui
npm ERR!     @herakles/customer-facing-ui@1.0.1
npm ERR!     node_modules/@herakles/customer-facing-ui
npm ERR!       workspace packages/customer-facing-ui from the root project
```

This is due to changes to package that has not reached 1.0.0 are treated as breaking changes: https://michaelsoolee.com/npm-pre-1-caret-rules/

**Comment by JonatanSalas** [comment]
@florianbepunkt as a workaround for now until I figure out, use `--force` when installing this package. I'll do a deep dive today and try to fix it ASAP.

**Comment by florianbepunkt** [comment]
@JonatanSalas Thank you. If you need help, let me know. Unfortunately we cannot use `--force` as a workaround, since npm is called by our dependency management tool (renovate.js), so we can't control the execution params.

**Comment by JonatanSalas** [comment]
@florianbepunkt If you want to help me by making a PR it's super welcome, this week I'm pretty busy :(

**Comment by florianbepunkt** [comment]
@JonatanSalas I can provide a PR. But I think we are caught between a rock and a hard place here...  a package that has not reached version 1.0 is unstable (in semver).

I can add a version constraint like `0.x.x` or `<1.0.0`. This would allow for people to keep their dependencies up to date but also introduce a slight chance of breaking things, if `@zxing/browser` or `@zxing/library` introduce breaking changes (which they could, staying semver-compliant).

Another approach would be for this lib to add them as dependencies (instead of peer deps). But then this would shift the maintenance burden of keeping these up to date to this library.

Do you have preferences?

**Comment by JonatanSalas** [comment]
In our case, we're trying to avoid maintaining this dependencies attached to our library, we want to give some freedom for our users to choose which version of zxing use or upgrade faster if any issue detected. 

So I think that adding a version constraint would be the choice, even with the risky things that can come up if a breaking change happens, but we're following up zxing library API so I think that if something like this happen we would be able to fix it faster.

**Comment by buffcode** [comment]
How about adding it as a dependency and configure Dependabot as GitHub action to keep this (and other dependencies) up to date?

Would kill two birds with one stone IMHO.

**Comment by JonatanSalas** [comment]
I've followed @buffcode since his point has convinced me. I've released v5, since this change was a breaking one. @florianbepunkt let me know if upgrading to the latest version fixes the issue for you `npm i @blackbox-vision/react-qr-reader@5.0.0`

**Comment by florianbepunkt** [comment]
@JonatanSalas Yes, this works fine. Thank you.
