### ISSUE TITLE
Doesn't work on Samsung Galaxy Note10+

### ISSUE THREAD

**Issue by valcho** [BlackBoxVision/react-qr-reader#2]
Thank you for the amazing React component! It works on virtually any device I've had the chance to test it on. 👏 Sadly, I am facing issues making it run successfully on the Samsung Galaxy Note10+ using Chrome.

## Expected Behavior
I expect the component to work like it does on my OnePlus 7 Pro or my colleague's iPhone X. Have the browser present the option to give the camera permission and then receive a video feed that's awaiting to scan a QR code.

## Actual Behavior
I have a button which says "Log in with a QR code" and it fires a Qr Reader modal. Then, it returns this error:
![image](https://user-images.githubusercontent.com/1886433/92372934-4f415180-f106-11ea-80f5-e2919c54adfb.png
 

## Steps to Reproduce the Problem

  1. Render the `QrReader` on a Galaxy Note 10+ 

## Specifications

  - Version: 2.0.0
  - Platform: Samsung Galaxy Note 10+ (Android 10)
  - Subsystem: Chrome 85.0.4183.81

Here's the code I'm using:

```js
<QrReader
       onScan={handleCameraScan}
       onError={handleCameraError}
       style={qrReaderStyle}
       facingMode="environment"
       resolution={640}
       ViewFinder={() => null}
    />

```

Thank you! 🙌

**Comment by JonatanSalas** [comment]
@valcho thanks for reporting this issue and the detailed information. We'll try to do our best to fix ASAP.

**Comment by JonatanSalas** [comment]
@valcho I'm currently working on a rewrite to use zxing-library which is a more stable library for QR Scanning, this will also help to iterate further and reduce bugs.

**Comment by JonatanSalas** [comment]
I'm going to push a hot-fix to master, we've the `getDeviceId` logic wrong. 

Our approach was to filter and took the first one, the issue there is that we could get a camera device ID that doesn't support streaming. 

Since browsers doesn't give a pretty good API to determine if camera device supports video-streaming, the way to fix is trying to open a stream in any camera that matches the `facingMode` prop. If any throws an error related to streaming we marked as non-streaming support and we stay with the ones that support it. 

We'll need to test it a little more in more devices. I've tested this approach in BrowserStack using the same device you specify and I've made it work as expected.

**Comment by JonatanSalas** [comment]
I've published a newer version to NPM, you can try it:
 
```bash
npm i @blackbox-vision/react-qr-reader@2.0.2
```

Hope it solves your issue!

**Comment by JonatanSalas** [comment]
For faster testing, you can check via storybook that I've recently deployed too: https://blackboxvision.github.io/react-qr-reader/?path=/story/qrreader--choose-facing-mode

**Comment by valcho** [comment]
@JonatanSalas **thank you** for your timely work on this issue, but sadly it still persists on Samsung Galaxy S20e and Galaxy Note 10+ devices with the same error: `Could not start video source.`

I tested this with v2.0.2 as instructed, but to no avail. Do you have any suggestions why that might be or how I could debug it? It seems to be Samsung-specific issue. Both its built-in Samsung Internet *and* Google Chrome browsers return the same error.

**Comment by valcho** [comment]
Here are some finding after a debugging session. 
![image](https://user-images.githubusercontent.com/1886433/93212142-dcba1c80-f76a-11ea-8d93-873007b0e7a9.png)
This screenshot is from 2.0.2. The `DOMException `"Could not start video stream" happens when the `getUserMedia` call is await'ed with the payload (as shown in the tooltip).

`2.0.2` has another problem on Safari (iMac) which causes it to both recognize the barcode but also throw an error which causes infinite App.tsx-level refreshes. This appears to be because even though **an error is thrown** and we hide the modal, it's actually **still running** in the background dozens of times every second, throwing an error every time.

I'm out of ideas why this is happening 😭

**Comment by JonatanSalas** [comment]
@valcho I've released v3 this weekend which has a rewrite to use zxing library instead of jsqr. In the newer version we removed the `onScan` and the `onError` callback, we introduced `onResult` which gives you the `result`, `error` and also the instance of the `codeReader` so you can stop manually the continues scanning process.

**Comment by JonatanSalas** [comment]
Today I'm a little busy, but, if you want, we can schedule a call for tomorrow, so we can check a little deeper the issue you're facing.

**Comment by valcho** [comment]
@JodusNodus Thank you and sorry for the late reply. Does tomorrow, Friday work for you?

**Comment by JonatanSalas** [comment]
I've been working on a re implementation to give the ability to pass a `constraints` prop, that should give more control on how to access the camera, and the constraints related to it. 

You can see here https://github.com/BlackBoxVision/react-qr-reader/tree/next
