### ISSUE TITLE
Example Usage or Demo doesn't work?

### ISSUE THREAD

**Issue by heikkikurkela** [BlackBoxVision/react-qr-reader#5]
### Expected Behavior
Example Usage or Demo should work as such.

### Actual Behavior
'NoDeviceFoundException' error.

### Steps to Reproduce the Problem
Render the QrReader

### Specifications
- Versions: @blackbox-vision/react-qr-reader@3.0.0,  @zxing/library@0.17.1
- Browser: Chrome 85.0.4183.83
- Platforms: Samsung Galaxy S8 or Laptop PC with webcam

Here's the code I'm using:

```
<QrReader
        onResult={(result, error) => {
          if (!!result) {
            setData(result?.text);
          }
          if (!!error) {
            console.info(error);
          }
        }}
        style={{ width: '100%' }}
      />
```

Thank you!

**Comment by Too-Far** [comment]
I am having the exact same issue. Anyone know of a fix?

**Comment by JonatanSalas** [comment]
Setting `facingMode` to value `user` should work. We're going to make that value default in the next release.

**Comment by JonatanSalas** [comment]
I've fixed this issue and make a newer release, you can check it out here working: https://codesandbox.io/s/busy-kirch-vp5c0?file=/src/App.js

To get the fix you should do: `npm i --save @blackbox-vision/react-qr-reader@3.0.1`

**Comment by Too-Far** [comment]
Thank you for the quick reply! I think I must be missing something, as I am still getting the same error, and your codesandbox link also has the error in the console

**Comment by JonatanSalas** [comment]
We've working on a fully reimplementation that fixes most of the issues.
